version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - NODE_ENV=production
    restart: always
    depends_on:
      - db

  db:
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=your_
      - MYSQL_USER=your_
      - MYSQL_PASSWORD=
    volumes:
      - ./db_data:/var/lib/mysql
